CREATE TABLE IF NOT EXISTS tb_sim_79(
	id             SERIAL PRIMARY KEY,
	ANO            INTEGER,
	REGISTRO       INTEGER,
	DATAREG        TIMESTAMP WITHOUT TIME ZONE,
	TIPOBITO       INTEGER,
	DATAOBITO      TIMESTAMP WITHOUT TIME ZONE,
	ESTCIVIL       INTEGER,
	SEXO           INTEGER,
	DATANASC       TIMESTAMP WITHOUT TIME ZONE,
	IDADE          INTEGER,
	LOCOCOR        INTEGER,
	MUNIOCOR       INTEGER,
	OCUPACAO       INTEGER,
	INSTRUCAO      INTEGER,
	OCUPPAI        INTEGER,
	INSTRPAI       INTEGER,
	OCUPMAE        INTEGER,
	IDADEMAE       INTEGER,
	INSTRMAE       INTEGER,
	FILHVIVOS      INTEGER,
	FILHMORT       INTEGER,
	SEMANGEST      INTEGER,
	TIPOGRAV       INTEGER,
	TIPOPARTO      INTEGER,
	PESONASC       DOUBLE PRECISION,
	ASSISTMED      INTEGER,
	ATESTANTE      INTEGER,
	EXAME          INTEGER,
	CIRURGIA       INTEGER,
	NECROPSIA      INTEGER,
	CAUSABAS       VARCHAR,
	TIPOVIOL       INTEGER,
	TIPOACID       INTEGER,
	ACIDTRAB       INTEGER,
	LOCACID        INTEGER,
	CRITICA        INTEGER,
	UFINFORM       INTEGER
);


-- A partir de 95
ALTER TABLE dados ADD COLUMN racacor Integer;
ALTER TABLE dados ADD COLUMN etnia Integer;
ALTER TABLE dados ADD COLUMN estciv Integer;
ALTER TABLE dados ADD COLUMN esc Integer;
ALTER TABLE dados ADD COLUMN ocup Integer;
ALTER TABLE dados ADD COLUMN codmunres Integer;
ALTER TABLE dados ADD COLUMN CODMUNOCOR Integer;
ALTER TABLE dados ADD COLUMN ESCMAE Integer;
ALTER TABLE dados ADD COLUMN QTDFILVIVO Integer;
ALTER TABLE dados ADD COLUMN QTDFILMORT Integer;
ALTER TABLE dados ADD COLUMN GRAVIDEZ Integer;
ALTER TABLE dados ADD COLUMN GESTACAO Integer;
ALTER TABLE dados ADD COLUMN PARTO Integer;
ALTER TABLE dados ADD COLUMN OBITOPARTO Integer;
ALTER TABLE dados ADD COLUMN PESO Integer;
ALTER TABLE dados ADD COLUMN OBITOGRAV Integer;
ALTER TABLE dados ADD COLUMN  Integer;
