CREATE TABLE IF NOT EXISTS tb_sim_95(
	id             SERIAL PRIMARY KEY,
	ANO            INTEGER,
	REGISTRO       INTEGER,
	DATAREG        TIMESTAMP WITHOUT TIME ZONE,
	TIPOBITO       INTEGER,
	DATAOBITO      TIMESTAMP WITHOUT TIME ZONE,
	ESTCIVIL       INTEGER,
	SEXO           INTEGER,
	DATANASC       TIMESTAMP WITHOUT TIME ZONE,
	IDADE          INTEGER,
	LOCOCOR        INTEGER,
	MUNIOCOR       INTEGER,
	OCUPACAO       INTEGER,
	INSTRUCAO      INTEGER,
	OCUPPAI        INTEGER,
	INSTRPAI       INTEGER,
	OCUPMAE        INTEGER,
	IDADEMAE       INTEGER,
	INSTRMAE       INTEGER,
	FILHVIVOS      INTEGER,
	FILHMORT       INTEGER,
	SEMANGEST      INTEGER,
	TIPOGRAV       INTEGER,
	TIPOPARTO      INTEGER,
	PESONASC       DOUBLE PRECISION,
	ASSISTMED      INTEGER,
	ATESTANTE      INTEGER,
	EXAME          INTEGER,
	CIRURGIA       INTEGER,
	NECROPSIA      INTEGER,
	CAUSABAS       VARCHAR,
	TIPOVIOL       INTEGER,
	TIPOACID       INTEGER,
	ACIDTRAB       INTEGER,
	LOCACID        INTEGER,
	CRITICA        INTEGER,
	UFINFORM       INTEGER
);

ALTER TABLE tb_sim_95 ADD COLUMN racacor Integer;
ALTER TABLE tb_sim_95 ADD COLUMN etnia Integer;
ALTER TABLE tb_sim_95 ADD COLUMN estciv Integer;
ALTER TABLE tb_sim_95 ADD COLUMN esc Integer;
ALTER TABLE tb_sim_95 ADD COLUMN ocup Integer;
ALTER TABLE tb_sim_95 ADD COLUMN codmunres Integer;
ALTER TABLE tb_sim_95 ADD COLUMN CODMUNOCOR Integer;
ALTER TABLE tb_sim_95 ADD COLUMN ESCMAE Integer;
ALTER TABLE tb_sim_95 ADD COLUMN QTDFILVIVO Integer;
ALTER TABLE tb_sim_95 ADD COLUMN QTDFILMORT Integer;
ALTER TABLE tb_sim_95 ADD COLUMN GRAVIDEZ Integer;
ALTER TABLE tb_sim_95 ADD COLUMN GESTACAO Integer;
ALTER TABLE tb_sim_95 ADD COLUMN PARTO Integer;
ALTER TABLE tb_sim_95 ADD COLUMN OBITOPARTO Integer;
ALTER TABLE tb_sim_95 ADD COLUMN PESO Integer;
ALTER TABLE tb_sim_95 ADD COLUMN OBITOGRAV Integer;