DELETE FROM sim.TB_ACIDTRAB;
DROP TABLE sim.TB_ACIDTRAB;

DELETE FROM sim.TB_ALTCAUSA;
DROP TABLE sim.TB_ALTCAUSA;

DELETE FROM sim.TB_ASSISTMED;
DROP TABLE sim.TB_ASSISTMED;

DELETE FROM sim.TB_ATESTANTE;
DROP TABLE sim.TB_ATESTANTE;

DELETE FROM sim.TB_CIRCOBITO;
DROP TABLE sim.TB_CIRCOBITO;

DELETE FROM sim.TB_CIRURGIA;
DROP TABLE sim.TB_CIRURGIA;

DELETE FROM sim.TB_ESC;
DROP TABLE sim.TB_ESC;

DELETE FROM sim.TB_ESC2010;
DROP TABLE sim.TB_ESC2010;

DELETE FROM sim.TB_ESCFALAGR1;
DROP TABLE sim.TB_ESCFALAGR1;

DELETE FROM sim.TB_ESCMAE;
DROP TABLE sim.TB_ESCMAE;

DELETE FROM sim.TB_ESCMAE2010;
DROP TABLE sim.TB_ESCMAE2010;

DELETE FROM sim.TB_ESCMAEAGR1;
DROP TABLE sim.TB_ESCMAEAGR1;

DELETE FROM sim.TB_ESTCIV;
DROP TABLE sim.TB_ESTCIV;

DELETE FROM sim.TB_ESTCIVIL;
DROP TABLE sim.TB_ESTCIVIL;

DELETE FROM sim.TB_EXAME;
DROP TABLE sim.TB_EXAME;

DELETE FROM sim.TB_FONTE;
DROP TABLE sim.TB_FONTE;

DELETE FROM sim.TB_FONTEINV;
DROP TABLE sim.TB_FONTEINV;

DELETE FROM sim.TB_GESTACAO;
DROP TABLE sim.TB_GESTACAO;

DELETE FROM sim.TB_GRAVIDEZ;
DROP TABLE sim.TB_GRAVIDEZ;

DELETE FROM sim.TB_INSTRUCAO;
DROP TABLE sim.TB_INSTRUCAO;

DELETE FROM sim.TB_LOCACID;
DROP TABLE sim.TB_LOCACID;

DELETE FROM sim.TB_LOCOCOR;
DROP TABLE sim.TB_LOCOCOR;

DELETE FROM sim.TB_MORTEPARTO;
DROP TABLE sim.TB_MORTEPARTO;

DELETE FROM sim.TB_NECROPSIA;
DROP TABLE sim.TB_NECROPSIA;

DELETE FROM sim.TB_OBITOGRAV;
DROP TABLE sim.TB_OBITOGRAV;

DELETE FROM sim.TB_OBITOPARTO;
DROP TABLE sim.TB_OBITOPARTO;

DELETE FROM sim.TB_OBITOPUERP;
DROP TABLE sim.TB_OBITOPUERP;

DELETE FROM sim.TB_PARTO;
DROP TABLE sim.TB_PARTO;

DELETE FROM sim.TB_RACACOR;
DROP TABLE sim.TB_RACACOR;

DELETE FROM sim.TB_SEMANGEST;
DROP TABLE sim.TB_SEMANGEST;

DELETE FROM sim.TB_SEXO;
DROP TABLE sim.TB_SEXO;

DELETE FROM sim.TB_TIPOACID;
DROP TABLE sim.TB_TIPOACID;

DELETE FROM sim.TB_TIPOBITO;
DROP TABLE sim.TB_TIPOBITO;

DELETE FROM sim.TB_TIPOGRAV;
DROP TABLE sim.TB_TIPOGRAV;

DELETE FROM sim.TB_TIPOPARTO;
DROP TABLE sim.TB_TIPOPARTO;

DELETE FROM sim.TB_TIPOVIOL;
DROP TABLE sim.TB_TIPOVIOL;

DELETE FROM sim.TB_TPMORTEOCO;
DROP TABLE sim.TB_TPMORTEOCO;

DELETE FROM sim.TB_TPOBITOCOR;
DROP TABLE sim.TB_TPOBITOCOR;

DELETE FROM sim.TB_TPPOS;
DROP TABLE sim.TB_TPPOS;

DELETE FROM sim.TB_TPRESGINFO;
DROP TABLE sim.TB_TPRESGINFO;

DROP SCHEMA IF EXISTS sim;